#!/bin/bash
set -x


OI=/var/lib/openinfoman
USERNAME=oi
BASEX=$OI/bin/basex

SFS=("stored_query_definitions/export_organizations_to_csv.xml" )


for SF in ${SFS[@]}
do
  cd $OI
  $OI/resources/scripts/install_stored_function.php $OI/resources/$SF 
  if [[ $? != 0 ]]; then exit 1; fi
done

chown -R $USERNAME:$USERNAME $OI